import { Hotel } from './model';

export const hotelsData: Hotel[] = [
  {
    id: 1,
    image: '/hotels/mi-pata-pet-hotel.webp',
    name: 'Mi Pata Pet Hotel',
    phoneContact: '(+51) 987 507 189',
    address: 'Av. Los Álamos 183, Chilca 15870',
    email: 'contacto@mipatapethotel.net',
    rating: 5,
    ratingCount: 8,
    minPrice: 55,
    maxPrice: 100,
    link_page: 'https://www.mipatapethotel.net/',
  },
  {
    id: 2,
    image: '/hotels/wau-hotel.webp',
    name: 'Wau Hotel',
    phoneContact: '(+51) 994 824 066',
    address: 'Calle Los Cactus, Mz. Q, lote 15A',
    email: 'reservas@wau.pe',
    rating: 5,
    ratingCount: 8,
    minPrice: 55,
    maxPrice: 100,
    link_page: 'https://www.hospedajeparaperros.com/',
  },
  {
    id: 3,
    image: '/hotels/pets-camp.webp',
    name: 'PetsCamp',
    phoneContact: '(+51) 978 375 238',
    address: 'Lurín, Lima, Peru',
    email: 'reservas@petscampperu.com',
    rating: 5,
    ratingCount: 8,
    minPrice: 55,
    maxPrice: 100,
    link_page: 'https://petscampperu.com/',
  },
  {
    id: 4,
    image: '/hotels/doggy-camp.webp',
    name: 'Doggy Camp',
    phoneContact: '(+51) 999 055 841',
    address: 'Huachipa, Lima',
    email: 'doggycamp@outlook.com',
    rating: 5,
    ratingCount: 8,
    minPrice: 55,
    maxPrice: 100,
    link_page: 'https://www.thedoggycamp.com/',
  },
  {
    id: 5,
    image: '/hotels/petit-lodgel.webp',
    name: 'Petit Lodgel',
    phoneContact: '(+51) 966 132 594',
    address: 'Km 80 Panamericana Sur, Mala',
    email: 'contacto@mipatapethotel.net',
    rating: 5,
    ratingCount: 8,
    minPrice: 55,
    maxPrice: 100,
    link_page: 'https://petitlodge.com/',
  },
];
