import { PetFriendly } from './model';

export const petFriendlyData: PetFriendly[] = [
  {
    id: 2,
    title: 'La Bodega Verde',
    adress: 'Jr. Sucre 335A Barranco (Mascotas bienvenidas)',
    link_page: 'https://www.facebook.com/labodegaverde',
    phone: '(01) 2478804',
    pet_place_type_id: 2,
    location_id: 757,
    image_card: 'pf2_bodega_verde_87562.jpg_master',
    image_detail: 'pf2_bodega_verde_header_dsc0025e.jpg',
    description:
      'Un espacio acogedor para disfrutar sin apuros de una propuesta saludable y artesanal, creado con amor para que puedas darte el tiempo de estar bien.',
    price_range: 'S/. 27 - S/. 51',
    schedule: 'lunes a domingo de 8:00 a.m. a 10:00 p.m.',
    food_type: 'Café, Delicatessen',
    location: {
      id: 757,
      latitude: '-12.148210',
      longitude: '-77.022489',
      country: 'Perú',
      city: 'Lima',
      department: 'Lima',
      zipcode: '',
      province: 'Lima',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 3,
    title: 'Cerato Café',
    adress: 'Av. Húsares de Junin 561, Jesús María 15072',
    link_page: 'https://www.facebook.com/ceratocafe/',
    phone: '(01) 4240179',
    pet_place_type_id: 2,
    location_id: 759,
    image_card: 'petFriendlyPictureCard-3-bodega-verde.jpeg',
    image_detail: 'petFriendlyPictureDetail-3-bodega-verde.jpeg',
    description:
      'Una cafetería cultural PETFRIENDLY en el que te sentirás como en casa. Acompañada del mejor servicio presentamos una deliciosa carta dulce y salada.',
    price_range: 'S/. 27 - S/. 51',
    schedule: 'lunes a domingo de 9:00 a.m. a 9:00 p.m.',
    food_type: 'Café, Delicatessen',
    location: {
      id: 759,
      latitude: null,
      longitude: null,
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Jesús María',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 45,
    title: 'el bigote coffee & waffles',
    adress: 'Av. Almte. Miguel Grau 1460, Lima 15063',
    link_page: null,
    phone: '999 700 904',
    pet_place_type_id: 2,
    location_id: 1052,
    image_card: 'pf45_el bigote.jpg_master',
    image_detail: null,
    description:
      'Un agradable lugar, el cual se especializa en los waffles, con un ambiente muy agradable y juegos de mesa para pasar un grato momento y lo mejor de todo es que puedes entrar con tus engreidos ',
    price_range: '-',
    schedule: '10:00 - 22:00',
    food_type: 'waffles',
    location: {
      id: 1052,
      latitude: '-12.138212',
      longitude: '-77.022313',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 51,
    title: 'HEFFERco',
    adress: 'Av. Almte. Miguel Grau 1450, Lima 15063',
    link_page: null,
    phone: ' 997 374 530',
    pet_place_type_id: 2,
    location_id: 1062,
    image_card: 'pf51_HEFFER.jpg_master',
    image_detail: 'pf51_HEFFER2.jpg',
    description:
      'un ambiente agradable con buena musica, para tomar unos tragitos y disfrutar de unas ricas hamburguesas o costillas ',
    price_range: "'",
    schedule: '12-22',
    food_type: 'Hamburguesas',
    location: {
      id: 1062,
      latitude: '-12.138199',
      longitude: '-77.022329',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco ',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 52,
    title: 'SSUKS Surf Shop',
    adress: 'Av. Almte. Miguel Grau 1420, Barranco 15063',
    link_page: null,
    phone: '965 890 641',
    pet_place_type_id: 1,
    location_id: 1068,
    image_card: 'pf52_SSUKS 2.jpeg_master',
    image_detail: 'pf52_SSUK.jpeg',
    description:
      'Una tienda de surf, en el que podras encontrar tablas de todo tipo, indumentaria, ropa y demas.',
    price_range: '-',
    schedule: '10:30 - 20:00',
    food_type: '-',
    location: {
      id: 1068,
      latitude: '-12.137645',
      longitude: '-77.022361',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 53,
    title: 'La Casa de Kanu',
    adress: 'Av San Martin 670, Barranco 15063',
    link_page: null,
    phone: '997 265 258',
    pet_place_type_id: 1,
    location_id: 1069,
    image_card: 'pf53_Kanu.jpeg_master',
    image_detail: null,
    description:
      'un lugar muy cool, donde encontraras diversos objetos vintage y muy geniales',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1069,
      latitude: '-12.139536',
      longitude: '-77.023398',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 54,
    title: 'MA Osteria',
    adress: ' Av. San Martín 689, Barranco LIMA 04, 15063',
    link_page: null,
    phone: '932 105 515',
    pet_place_type_id: 2,
    location_id: 1070,
    image_card: 'pf54_MA.jpeg_master',
    image_detail: 'pf54_MA2.jpeg',
    description:
      'Restaurante Gourmet con un ambiente muy amigable y completamente Dog Lover',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1070,
      latitude: '-12.139376',
      longitude: '-77.023500',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 55,
    title: 'El Turco (Sede Barranco)',
    adress: 'Av San Martin 662, Barranco, Lima 15063',
    link_page: null,
    phone: '961 772 730',
    pet_place_type_id: 1,
    location_id: 1071,
    image_card: 'pf55_turco barranco.jpeg_master',
    image_detail: 'pf55_turco barranco.jpeg',
    description:
      'Barberia con ayuda personalizada a mejorar la imagen y ademas cuenta con productos de calidad para la barba y cabello. ',
    price_range: '-',
    schedule: '12-20',
    food_type: '-',
    location: {
      id: 1071,
      latitude: '-12.139784',
      longitude: '-77.023436',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 56,
    title: 'alobebe',
    adress: 'Jiron centenario 179',
    link_page: null,
    phone: '015589604',
    pet_place_type_id: 1,
    location_id: 1072,
    image_card: 'pf56_alobebe.jpeg_master',
    image_detail: 'pf56_alobebe3.jpeg',
    description:
      'Tienda muy bonita y simpatica en la que podrás encontrar todo tipo de ropa y demás, relacionado con tu bebé ',
    price_range: '-',
    schedule: '10:00 - 20:00',
    food_type: '-',
    location: {
      id: 1072,
      latitude: '-12.141034',
      longitude: '-77.023007',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 57,
    title: 'Amaru casa cultural',
    adress: 'Jiron Mariscal Jose Antonio de Sucre 317',
    link_page: null,
    phone: '999014351',
    pet_place_type_id: 1,
    location_id: 1073,
    image_card: 'pf57_amaru2.png_master',
    image_detail: 'pf57_amaru.jpg',
    description:
      'lugar muy interesante ubicado en el corazón de Barranco, en el cual podrás probar talleres de verano y otras actividades útiles ',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1073,
      latitude: '-12.148189',
      longitude: '-77.022881',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 58,
    title: 'Jade Rivera ',
    adress: 'Bajada de baños 349 ',
    link_page: null,
    phone: '958782860',
    pet_place_type_id: 2,
    location_id: 1074,
    image_card: 'pf58_jade2.png_master',
    image_detail: 'pf58_Jade Rivera.jpeg',
    description:
      'lugar de Street Art, ubicado en el corazon de barranco, un buen sitio para salir un poco de la rutina y probar algo nuevo ',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1074,
      latitude: '-12.160493',
      longitude: '-77.023589',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 59,
    title: 'El Gato Tulipan',
    adress: 'Bajada de Baños 350, Barranco 15063',
    link_page: null,
    phone: '957 284 447',
    pet_place_type_id: 2,
    location_id: 1076,
    image_card: 'pf59_Gato Tulipan 2.jpg_master',
    image_detail: 'pf59_Gato Tulipan 1.jpg',
    description:
      'agradable lugar ubicado cerca del puente de los suspiros, en el cual podras aprender musica y pasar un momento agradable lleno de arte, como su nonmbre lo dice, hay un gato que es el anfitrion del local ',
    price_range: '-',
    schedule: '11:00 - 23:00',
    food_type: '-',
    location: {
      id: 1076,
      latitude: '-12.149556',
      longitude: '-77.023193',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 60,
    title: 'Las Vecinas (Sede Barranco)',
    adress: 'Jirón Domeyer 219, Barranco 15063',
    link_page: null,
    phone: '(01) 4773253',
    pet_place_type_id: 3,
    location_id: 1077,
    image_card: 'pf60_las vecinas.jpg_master',
    image_detail: 'pf60_las vecinas 2.png',
    description:
      'Cafeteria agradable con un ambiente muy bueno para relajarse despues del trabajo o mientras uno pasea por las culturales calles de barranco ',
    price_range: '-',
    schedule: '8:00 - 21:00',
    food_type: '-',
    location: {
      id: 1077,
      latitude: '-12.147615',
      longitude: '-77.022371',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 61,
    title: 'AMA The Knit Specialist',
    adress: 'Bajada de Baños 349, Barranco, Lima, Peru',
    link_page: null,
    phone: '-',
    pet_place_type_id: 1,
    location_id: 1078,
    image_card: 'pf61_AMA.jpeg_master',
    image_detail: null,
    description:
      'Interesante y simpatico lugar en el cual podras conseguir diversas prendas diseñadas nada mas y nada menos, que con material de alpaca hecha a mano con mucho cariño.',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1078,
      latitude: '-12.149490',
      longitude: '-77.022817',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 62,
    title: 'Todo Surf Shop ',
    adress: 'Calle Berlín 260 Miraflores ',
    link_page: null,
    phone: '950 950 409',
    pet_place_type_id: 1,
    location_id: 1079,
    image_card: 'pf62_Todo Surf Shop.jpeg_master',
    image_detail: 'pf62_todo surf shop 2.jpg',
    description:
      'tienda de surf muy cool en el cual podras encontrar todo lo relacionado a dicho deporte, ademas de prendas de ropa super cheveres, puedes venir tranquilamente con tu engreido sin ningun problema',
    price_range: '-',
    schedule: '11:00 - 20:00',
    food_type: '-',
    location: {
      id: 1079,
      latitude: '-12.121107',
      longitude: '-77.032368',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 63,
    title: 'La Calaca, Paletas Mexicanas',
    adress: 'Calle Berlin 325, Miraflores 15074',
    link_page: null,
    phone: '(01) 2649019',
    pet_place_type_id: 2,
    location_id: 1080,
    image_card: 'pf63_calaca 1.jpg_master',
    image_detail: 'pf63_calaca 2.jpg',
    description:
      'heladeria de paletas mexicanas muy rico en el cual tambien venden paletas para perritos, recontra innovador y super pet lover',
    price_range: '-',
    schedule: '12:00 - 20:00',
    food_type: 'Paletas',
    location: {
      id: 1080,
      latitude: '-12.121123',
      longitude: '-77.032766',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 64,
    title: 'Choco Museo (Miraflores, Berlin)',
    adress: 'Calle Berlin 375',
    link_page: null,
    phone: '(01) 4459708',
    pet_place_type_id: 2,
    location_id: 1081,
    image_card: 'pf64_choco museo 1.jpg_master',
    image_detail: 'pf64_choco museo 2.jpg',
    description:
      'Museo de chocolate en el cual podras degustar de todo tipo de cacao, muy cultural ',
    price_range: '-',
    schedule: '09:00 - 20:30 ',
    food_type: 'chocolates',
    location: {
      id: 1081,
      latitude: '-12.120601',
      longitude: '-77.033347',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 65,
    title: 'Ohana Good Mood Food (Miraflores)',
    adress: 'Jorge Chavez, Miraflores',
    link_page: null,
    phone: '(01) 7277315',
    pet_place_type_id: 2,
    location_id: 1082,
    image_card: 'pf65_ohana3.jpeg_master',
    image_detail: 'pf65_ohana 1.png',
    description:
      'Lugar super saludable de comida hawaiana, pokes y acai bowls, muy recomendado para las personas que les gusta llevar una vida saludable.',
    price_range: '-',
    schedule: '8:00 - 22:00',
    food_type: 'Hawaiana',
    location: {
      id: 1082,
      latitude: '-12.119231',
      longitude: '-77.036844',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 66,
    title: 'Detox Express Miraflores',
    adress: 'Jorge Chávez 125, Miraflores',
    link_page: null,
    phone: '978 002 955',
    pet_place_type_id: 2,
    location_id: 1083,
    image_card: 'pf66_detox peru.jpeg_master',
    image_detail: null,
    description:
      'Lugar muy saludable y nutritivo en el cual podras tranquilamente comerte una ensalada o un muy buen sandwich recontra fitness junto a tu mascota',
    price_range: '-',
    schedule: '08:00 - 20:00',
    food_type: '-',
    location: {
      id: 1083,
      latitude: '-12.119285',
      longitude: '-77.036846',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 67,
    title: 'Skate Outlet (Sede Miraflores) ',
    adress: ' Av. Perez Aranibar 554, Miraflores 15074',
    link_page: null,
    phone: '(01) 2535162',
    pet_place_type_id: 1,
    location_id: 1084,
    image_card: 'pf67_sk8 outlet miraflores.jpg_master',
    image_detail: 'pf67_sk8 outlet 2.png',
    description:
      'tienda de skate muy buena donde te van a asesorar sobre tablas y styling muy bueno de ropa para montar skate, es muy completa la tienda y lo mejor es que son pet friendly ',
    price_range: '-',
    schedule: '11:00 - 20:30 ',
    food_type: '-',
    location: {
      id: 1084,
      latitude: '-12.115220',
      longitude: '-77.045957',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 68,
    title: 'Pizza Rock ',
    adress: 'Av. del Ejército 695, Miraflores 15074',
    link_page: null,
    phone: '962 324 289',
    pet_place_type_id: 2,
    location_id: 1085,
    image_card: 'pf68_pizza rock.jpg_master',
    image_detail: 'pf68_pizza rock 2.jpg',
    description:
      'restaurante de pizzas tematico de rock donde hay shows y demas sorpresas, para pasarlo bien en familia, con amigos o con tu perrito ',
    price_range: '-',
    schedule: '18:00 - 01:00',
    food_type: 'Pizza ',
    location: {
      id: 1085,
      latitude: '-12.114740',
      longitude: '-77.047083',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 69,
    title: 'Tierra Baldia - Restaurante Cultural ',
    adress: 'Av. del Ejército 847, Miraflores 15074',
    link_page: null,
    phone: '999 134 343',
    pet_place_type_id: 2,
    location_id: 1086,
    image_card: 'pf69_tierra-baldia 1.jpg_master',
    image_detail: 'pf69_tierra baldia 2.png',
    description:
      'lugar cultural en el cual podras leerte un buen libro o disfrutar de buena musica, en compañia de tu mascota, mientras disfrutas de un buen cafe o lo que ofrezca la carta',
    price_range: '-',
    schedule: '8:00 - 23:00',
    food_type: '-',
    location: {
      id: 1086,
      latitude: '-12.113605',
      longitude: '-77.048155',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 70,
    title: 'Chugus',
    adress: 'Av La Paz 343 ',
    link_page: null,
    phone: '999 902 594',
    pet_place_type_id: 2,
    location_id: 1087,
    image_card: 'pf70_chugus 2.jpeg_master',
    image_detail: 'pf70_chugus.png',
    description:
      'hamburgueseria muy rica y contundente en la cual podras ir con tu engreido para romper la dieta ',
    price_range: '-',
    schedule: '12-22',
    food_type: 'Hamburguesas',
    location: {
      id: 1087,
      latitude: '-12.120889',
      longitude: '-77.026752',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 71,
    title: 'Tradiciones',
    adress: 'Av La Paz cdra 3',
    link_page: null,
    phone: '-',
    pet_place_type_id: 2,
    location_id: 1088,
    image_card: 'pf71_tradiciones.jpeg_master',
    image_detail: null,
    description:
      'Lugar de venta de piqueos, lacteos, embutidos y frutos secos de Peru, 100% tradicionales',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1088,
      latitude: '-12.121267',
      longitude: '-77.026833',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 72,
    title: 'maitea',
    adress: 'Av la Paz 592',
    link_page: null,
    phone: '(01) 677 4612 / 990928394',
    pet_place_type_id: 2,
    location_id: 1089,
    image_card: 'pf72_maitea.jpg_master',
    image_detail: null,
    description:
      'lugar muy interesante de arte, cerveza, vinos y demas cosas ricas',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1089,
      latitude: '-12.123017',
      longitude: '-77.026892',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 73,
    title: 'Miscele',
    adress: ' Av. la Paz 580, Miraflores 15074',
    link_page: null,
    phone: '-',
    pet_place_type_id: 2,
    location_id: 1090,
    image_card: 'pf73_Miscele A.jpeg_master',
    image_detail: 'pf73_Miscele B.jpeg',
    description:
      'Buen lugar para refrescarte de una manera saludable. En Miscele encontrarás smoothies, helados, café y cold brew',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1090,
      latitude: '-12.122885',
      longitude: '-77.026897',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 74,
    title: 'Cafe 347',
    adress: 'Avenida Ernesto Diez Canseco 347, Miraflores 15074',
    link_page: null,
    phone: '(01) 4440279',
    pet_place_type_id: 3,
    location_id: 1091,
    image_card: 'pf74_Cafe 347 A.jpg_master',
    image_detail: 'pf74_Cafe 347 B.jpg',
    description:
      'cafeteria muy simpatica con unos cheesecakes que son espectaculares, muy simpatico ',
    price_range: '-',
    schedule: '08:00 - 22:30',
    food_type: 'cheesecake',
    location: {
      id: 1091,
      latitude: '-12.122152',
      longitude: '-77.026914',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 75,
    title: 'A1 Studio ',
    adress: 'Avenida Ernesto Diez Canseco 285, Miraflores 15074',
    link_page: null,
    phone: '923 968 943',
    pet_place_type_id: 1,
    location_id: 1092,
    image_card: 'pf75_A1 2.jpeg_master',
    image_detail: 'pf75_A1 studio 1.png',
    description:
      'Estudio de tatuajes y Barberia, ambos servicios juntos en un mismo lugar, una idea muy innovadora y revolucionaria. Si lo que quieres es estilo, debes ir con ellos. Ademas, son amantes de las mascotas',
    price_range: '-',
    schedule: '10:00 - 22:00 ',
    food_type: '-',
    location: {
      id: 1092,
      latitude: '-12.122168',
      longitude: '-77.027868',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 76,
    title: 'GATTI - Productos Naturales (Miraflores)',
    adress: ' Av. La Merced 109 Miraflores, Lima',
    link_page: null,
    phone: '923 573 039',
    pet_place_type_id: 1,
    location_id: 1093,
    image_card: 'pf76_GATTI 2.jpeg_master',
    image_detail: 'pf76_GATTI.png',
    description:
      'Tienda de Productos Naturales : aceites, helados, galletas y demas. Es el lugar fundamental para alguien que lleve una vida saludable o quiera animarse a llevarla y lo mejor de todo es que se acepta el ingreso con mascotas. ',
    price_range: '-',
    schedule: '9:00 - 21:00',
    food_type: '-',
    location: {
      id: 1093,
      latitude: '-12.127925',
      longitude: '-77.009452',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 77,
    title: 'Vapering Store',
    adress: 'Calle Sor Tita 110 Miraflores',
    link_page: null,
    phone: '913025081/923722774',
    pet_place_type_id: 1,
    location_id: 1094,
    image_card: 'pf77_Vstore.jpg_master',
    image_detail: null,
    description:
      'tienda de cigarros electronicos y vapes, en el cual seras asesorado de la mejor manera en base a tus gustos y tus ganas de cambiar el cigarro por algo menos dañino. Ademas cuenta con una variedad enorme de sabores de vape para todos los gustos.',
    price_range: '-',
    schedule: '11:00 - 21:00',
    food_type: '-',
    location: {
      id: 1094,
      latitude: '-12.127981',
      longitude: '-77.008995',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 78,
    title: "Galliani's Glamour",
    adress: 'Av. Alfredo Benavides 2250, Miraflores 15048',
    link_page: null,
    phone: '(01) 5606588',
    pet_place_type_id: 1,
    location_id: 1095,
    image_card: 'pf78_Gallianis 1.png_master',
    image_detail: null,
    description:
      'Lugar de Ropa femenina super top y de lo ultimo en moda, el mejor asesoramiento por parte de las vendedoras que son unas genias en todo lo que es styling y moda. Lo mejor en moda y diseño, lo encontraras aqui. ',
    price_range: '-',
    schedule: '09:00 - 21:00',
    food_type: '-',
    location: {
      id: 1095,
      latitude: '-12.128389',
      longitude: '-77.007184',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 79,
    title: 'JACK ROGERS  ',
    adress: 'Av Republica de Panama 5719 - Miraflores',
    link_page: null,
    phone: '(01)312 8116 / 993 762 089',
    pet_place_type_id: 1,
    location_id: 1096,
    image_card: 'pf79_Jack Rogers 2.jpeg_master',
    image_detail: 'pf79_Jack Rogers.jpg',
    description:
      'Barberia con tematica muy buena de pirata, en el cual seras asesorado de la mejor manera para llevar el look que vaya perfecto con tu estilo y tu forma de ser. Ademas de tener la tematica muy cool de piratas, son recontra dog lovers ',
    price_range: '-',
    schedule: '11:00 - 20:30 ',
    food_type: '-',
    location: {
      id: 1096,
      latitude: '-12.120735',
      longitude: '-77.018283',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 80,
    title: 'El FILETON ',
    adress: 'Av Roosevelt 5895 ',
    link_page: null,
    phone: '(01) 4465046',
    pet_place_type_id: 2,
    location_id: 1097,
    image_card: 'pf80_el fileton 2.jpeg_master',
    image_detail: 'pf80_El fileton 1.jpg',
    description:
      'Sangucheria clasica con un ambiente muy calido y amable, ademas de ser recontra pet lover',
    price_range: '-',
    schedule: '08:30 - 22:30',
    food_type: 'Sangucheria ',
    location: {
      id: 1097,
      latitude: '-12.121579',
      longitude: '-77.018108',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 81,
    title: 'RIVOLTA STREET PASTA',
    adress: 'Avenida Ernesto Diez Canseco 331',
    link_page: null,
    phone: '- ',
    pet_place_type_id: 2,
    location_id: 1098,
    image_card: 'pf81_rivolta 2.jpeg_master',
    image_detail: 'pf81_rivolta1.jpg',
    description:
      'Restaurante de Pastas super innovador en el cual tu puedes armar tu propia pasta, eligiendo el tipo de pasta, la salsa y agregar los topings que desees, para luego disfrutarla en un ambiente super comodo y tranquilo. Ubicado en el corazon de miraflores, es un lugar con muy buenas vibras, ademas de ser recontra pet friendly ',
    price_range: '-',
    schedule: '-',
    food_type: 'pastas',
    location: {
      id: 1098,
      latitude: '-12.122225',
      longitude: '-77.027134',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 102,
    title: 'POD HOUSE PERU',
    adress: ' av benavides 347 tienda 2 Cc expo centro, Miraflores',
    link_page: 'https://www.instagram.com/_podhouse_/',
    phone: '960 555 888',
    pet_place_type_id: 1,
    location_id: 1128,
    image_card: 'pf102_POD1.jpeg_master',
    image_detail: 'pf102_POD2.jpeg',
    description:
      'Una tienda de liquidos de Vape y cigarros electronicos, la cual cuenta con un area muy agradable, para pasar el rato con amigos, viendo partidos importantes o eventos deportivos importantes, mientras vapean y socializan. Cuentan con una gran variedad de liquidos, para todos los gustos. Muy recomendado ',
    price_range: '-',
    schedule: '10:00 - 21:00',
    food_type: '-',
    location: {
      id: 1128,
      latitude: '-12.124626',
      longitude: '-77.029716',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 103,
    title: 'Estacion Cafe de Luz ',
    adress: 'Simón Salguero 534, Santiago de Surco 15048',
    link_page: 'https://www.instagram.com/estacioncafedeluz/',
    phone: '-',
    pet_place_type_id: 2,
    location_id: 1129,
    image_card: 'pf103_Estacion Cafe 1.jpeg_master',
    image_detail: 'pf103_estacion cafe 2.jpg',
    description:
      'Agradable lugar para tomar uno de los mejores cafes y disfrutar de un bocado o un rico sandwich junto a tu mascota',
    price_range: '-',
    schedule: '8:00 - 20:00',
    food_type: '-',
    location: {
      id: 1129,
      latitude: '-12.130222',
      longitude: '-77.008417',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Surco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 104,
    title: 'Cigarrillo electronico Peru ',
    adress: 'Simón Salguero #540,Tienda #5, Santiago de Surco 15048',
    link_page: 'https://es-la.facebook.com/CigarrilloElectronico.com.pe/',
    phone: ' (01) 2678048',
    pet_place_type_id: 1,
    location_id: 1130,
    image_card: 'pf104_Cigarrillo electronico 1.jpeg_master',
    image_detail: null,
    description:
      'Tienda de cigarrillos electronicos de alta calidad en la cual seras asesorado por los vendedores, los cuales te daran muchas ideas a cerca del cigarro electronico que necesites',
    price_range: '-',
    schedule: '10:00 - 20:00',
    food_type: '-',
    location: {
      id: 1130,
      latitude: '-12.130282',
      longitude: '-77.008491',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Surco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 105,
    title: 'Matices',
    adress: 'Simón Salguero 558, Santiago de Surco 15048',
    link_page:
      'https://www.facebook.com/pages/category/Shopping---Retail/Matices-Obsekios-1527783654211120/',
    phone: '(01) 4482566',
    pet_place_type_id: 1,
    location_id: 1131,
    image_card: 'pf105_Matices.jpeg_master',
    image_detail: null,
    description:
      'Lugar en el cual podras encontrar todo lo necesario para el hogar, para poder darle un toque especial, el cual marcara la diferencia ',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1131,
      latitude: '-12.130270',
      longitude: '-77.007796',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Surco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 106,
    title: 'Cover Out Salon',
    adress: ' Sor Mate 298, Santiago de Surco 15048',
    link_page:
      'https://ro-ro.facebook.com/pages/category/Beauty--Cosmetic---Personal-Care/Cover-Out-Salon-381200369337981/posts/',
    phone: '(01) 2663165',
    pet_place_type_id: 1,
    location_id: 1132,
    image_card: 'pf106_Cover Out.jpeg_master',
    image_detail: 'pf106_Cover Out 2.jpg',
    description:
      'Agradable y simpatico salon de belleza en el cual, podras relajarte y engreirte con profesionales que te guiaran y asesoraran en encontrar el look perfecto ',
    price_range: '-',
    schedule: '09:30 - 20:00',
    food_type: '-',
    location: {
      id: 1132,
      latitude: '-12.130461',
      longitude: '-77.007499',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Surco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 107,
    title: 'Florería Essenza',
    adress: 'Simón Salguero 595, Santiago de Surco 15048',
    link_page: 'http://www.essenza.com.pe/',
    phone: '(01) 2734533',
    pet_place_type_id: 1,
    location_id: 1133,
    image_card: 'pf107_essenza1.jpeg_master',
    image_detail: 'pf107_essenza2.png',
    description:
      'Floreria muy agradable con mucha diversidad y variedad para escoger, para todos los gustos ',
    price_range: '-',
    schedule: '09:00 - 17:00',
    food_type: '-',
    location: {
      id: 1133,
      latitude: '-12.130410',
      longitude: '-77.007605',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Surco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 108,
    title: 'Punto Gourmet ',
    adress: 'Simon Salguero 507 ',
    link_page: 'https://es-la.facebook.com/PuntoGourmetOficial/',
    phone: '(01) 2738264',
    pet_place_type_id: 2,
    location_id: 1134,
    image_card: 'pf108_Punto Gourmet1.jpeg_master',
    image_detail: 'pf108_punto gourmet2.png',
    description:
      'Agradable tienda de pasteles, pan y muchas cosas muy ricas y nutritivas. Consta de mucha variedad de alimentos saludables y en relacion con el cuidado y la preservacion del medio ambiente ',
    price_range: '-',
    schedule: '10:30 - 20:30 ',
    food_type: '-',
    location: {
      id: 1134,
      latitude: '-12.130269',
      longitude: '-77.008560',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Surco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 119,
    title: 'Inmortal Art',
    adress: ' Calle Bajada Balta 138, Miraflores 15074',
    link_page: 'https://es-la.facebook.com/InmortalArtPeru/',
    phone: ' (01) 4462717',
    pet_place_type_id: 2,
    location_id: 1190,
    image_card: 'pf119_inmortal art.jpeg_master',
    image_detail: null,
    description:
      'estudio de tatuaje con una larga trayectoria con artistas muy experimentados, que te asesoraran en todo momento, para lograr tener el tatuaje exacto',
    price_range: '-',
    schedule: '10:00 - 20:00',
    food_type: '-',
    location: {
      id: 1190,
      latitude: '-12.123279',
      longitude: '-77.031898',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 126,
    title: 'Mar y Moda by Kuny ',
    adress: 'Malecón Balta 129, Miraflores 15074',
    link_page: 'https://es-la.facebook.com/KunySwimwear/',
    phone: '(01) 2410804',
    pet_place_type_id: 1,
    location_id: 1209,
    image_card: 'pf126_Mar y moda1.jpeg_master',
    image_detail: null,
    description:
      'tienda de ropa de baño muy bonita ubicada en bajada balta con una alta linea de la mas moderna ropa de baño para chicas ',
    price_range: '-',
    schedule: '11:30 - 14:00  15:00 - 20:30',
    food_type: '-',
    location: {
      id: 1209,
      latitude: '-12.123276',
      longitude: '-77.031925',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 127,
    title: 'Coyotes Tattoo',
    adress: ' Bajada Balta 127, Miraflores ',
    link_page: 'https://es-la.facebook.com/coyotestattoomiraflores/',
    phone: '(01) 2417593',
    pet_place_type_id: 1,
    location_id: 1211,
    image_card: 'pf127_coyote1.jpeg_master',
    image_detail: 'pf127_coyote2.png',
    description:
      'Estudio de tatuaje, pionero de dicho arte en Peru, en el cual encontraras a los mas experimentados artistas en miraflores, ubicado en la bajada balta',
    price_range: '-',
    schedule: '10:00 - 21:00',
    food_type: '-',
    location: {
      id: 1211,
      latitude: '-12.123171',
      longitude: '-77.031838',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 152,
    title: "Jank'a Cafe ",
    adress: 'Calle Porta 178, Miraflores 15074',
    link_page: 'https://es-la.facebook.com/Janka-Caf%C3%A9-1352545374845013/',
    phone: '949 260 983',
    pet_place_type_id: 3,
    location_id: 1240,
    image_card: 'pf152_Janka1.jpg_master',
    image_detail: 'pf152_janka2.jpg',
    description:
      'agradable lugar para tomarte un cafe junto a la compañia de tu mascota, muy recomendado por turistas ',
    price_range: '-',
    schedule: '09:00 - 20:00 ',
    food_type: '-',
    location: {
      id: 1240,
      latitude: '-12.123230',
      longitude: '-77.031227',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 153,
    title: 'Kalami Spa ',
    adress: 'Av. Almte. Miguel Grau 1121, Barranco',
    link_page: 'https://es-la.facebook.com/pages/Kalami-Spa/163636957903710',
    phone: '987 750 827',
    pet_place_type_id: 1,
    location_id: 1241,
    image_card: 'pf153_kalami.png_master',
    image_detail: null,
    description:
      'agradable sitio de spa, para disfrutar de los mejores masajes, servicio super recomendado ',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1241,
      latitude: '-12.139381',
      longitude: '-77.022915',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Barranco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 155,
    title: 'Danny Tattoo',
    adress: ' Pje. los Pinos 114, Miraflores 15074',
    link_page: 'https://www.instagram.com/dannytattooperu/',
    phone: ' (01) 4469666',
    pet_place_type_id: 2,
    location_id: 1243,
    image_card: 'pf155_danny1.jpeg_master',
    image_detail: null,
    description:
      'Estudio de tatuaje con gente muy buena onda que te dara la mejor atencion y querran a tu mascota como si fuera de ellos, recontra petlovers',
    price_range: '-',
    schedule: '10:00 - 21:00',
    food_type: '-',
    location: {
      id: 1243,
      latitude: '-12.122775',
      longitude: '-77.030484',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 156,
    title: 'Tu Chinindro',
    adress: 'Psje Los Pinos Miraflores',
    link_page: 'https://www.instagram.com/tuchinindroficial_/',
    phone: '-',
    pet_place_type_id: 2,
    location_id: 1244,
    image_card: 'pf156_chinindro.jpeg_master',
    image_detail: null,
    description:
      'Lugar de comida venezolana en el cual experimentaras un sabor unico y de la mejor atencion posible ',
    price_range: '-',
    schedule: '12:00 - 21:00',
    food_type: '-',
    location: {
      id: 1244,
      latitude: '-12.123968',
      longitude: '-77.030705',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 157,
    title: 'Monster Tea',
    adress: ' Pje. los Pinos 120, Miraflores ',
    link_page: 'https://www.instagram.com/monster.tea/',
    phone: '-',
    pet_place_type_id: 2,
    location_id: 1245,
    image_card: 'pf157_monster tea.jpeg_master',
    image_detail: 'pf157_monster tea 2.png',
    description:
      'Lugar de bubble tea, con un ambiente muy creativo y agradable, con el mejor trato ',
    price_range: '-',
    schedule: '11:00 - 23:00',
    food_type: '-',
    location: {
      id: 1245,
      latitude: '-12.123863',
      longitude: '-77.030658',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 158,
    title: 'GyRSalondeBelleza',
    adress: 'Calle Jose Galvez 126  Miraflores',
    link_page:
      'https://www.google.com.pe/search?rlz=1C2AWFC_enUS836US836&sxsrf=ALeKk02Ukxq9VTA8yWsXhJ3SMVF0FpTnMw:1582945096547&ei=ydJZXqioAYO95OUP3tcB&q=Sal%C3%B3n%20de%20belleza%2C%20Calle%20Jos%C3%A9%20Galvez%2C%20Miraflores&oq=salon+de+belleza+jose+gal&gs_l=psy-ab.1.2.0i22i30l2j38.119289.122268..125182...1.0..1.1113.7838.3-3j3j1j3j2......0....1..gws-wiz.......35i39j0j0i20i263..23%3A11-546g587j24%3A11-2g4.pKaAkj4lieQ&npsic=0&rflfq=1&rlha=0&rllag=-12121970,-77035500,378&tbm=lcl&rldimm=9544467984459351353&ved=2ahUKEwjvxbaB4vXnAhWUIrkGHZVFDL8QvS4wAXoECAsQKQ&rldoc=1&tbs=lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:2&rlst=f#rlfi=hd:;si:9544467984459351353;mv:[[-12.121015199999999,-77.0317093],[-12.1228828,-77.0392909]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:2',
    phone: '963 100 752',
    pet_place_type_id: 2,
    location_id: 1246,
    image_card: 'pf158_GyR.jpeg_master',
    image_detail: null,
    description:
      'clasico salon de belleza ubicado en la primera cuadra de berlin, donde te atenderan gustosamente acompañado de tu mascota',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1246,
      latitude: '-12.122604',
      longitude: '-77.032085',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 159,
    title: 'La Fruteria',
    adress: 'Av. Alfredo Benavides 250, Miraflores 05101',
    link_page:
      'https://www.google.com.pe/search?hl=es&sxsrf=ALeKk02kMigS9Ca_GY2mDwJUJx5s2p6d9Q%3A1582945245655&source=hp&ei=3dNZXqyJJq6v5OUPoYWbwA4&q=La+Fruter%C3%ADa%2C+Avenida+Alfredo+Benavides%2C+Miraflores&oq=La+Fruteria+bena&gs_l=psy-ab.3.1.0i22i30j38.2076.6748..10035...1.0..0.700.8528.4-4j11j1......0....1..gws-wiz.......35i39j0j0i131j0i67j0i131i67j0i20i263j0i203..23%3A0g422g463g511g529g492g562g536g512g549g595g542j24%3A0g1g1g1g1g1g1g1g1g1g5g2.IPpwCrOmjXo',
    phone: '984 673 853',
    pet_place_type_id: 2,
    location_id: 1247,
    image_card: 'pf159_la fruteria.jpeg_master',
    image_detail: null,
    description:
      'La frutería es una cafetería - minimarket en donde puedes encontrar productos de consumo diario. Además cuenta con una variedad de frutas de temporada, jugos de fruta, y postres preparados aquí mismo',
    price_range: '-',
    schedule: '07:30 - 22:00 ',
    food_type: '-',
    location: {
      id: 1247,
      latitude: '-12.124377',
      longitude: '-77.030735',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 160,
    title: 'KM Barber Classic',
    adress: ' Benavides 347 Piso 1 Local 15',
    link_page: 'https://www.instagram.com/kmbarberclassic/',
    phone: '917-349-675 ',
    pet_place_type_id: 1,
    location_id: 1248,
    image_card: 'pf160_KM1.jpeg_master',
    image_detail: 'pf160_KM2.jpeg',
    description:
      'Servicio altamente recomendado, muy buen trato en todo momento. Un ambiente muy agradable para pasar un buen rato mientras te asesoran de la mejor manera para tener el look que necesitas y que va a ir contigo ',
    price_range: '-',
    schedule: '08:00 - 22:00',
    food_type: '-',
    location: {
      id: 1248,
      latitude: '-12.124311',
      longitude: '-77.029920',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 161,
    title: 'Hawi Poke Bowls | Miraflores',
    adress: 'C.C. Expocentro, Av. Alfredo Benavides 347, Miraflores 15074',
    link_page: 'https://www.instagram.com/hawipoke.pe/',
    phone: '948 175 368',
    pet_place_type_id: 2,
    location_id: 1249,
    image_card: 'pf161_hawi2.jpeg_master',
    image_detail: 'pf161_hawi1.jpg',
    description:
      'Lugar recontra saludable de poke bowls, en el cual seran bienvenidos todos los perritos ',
    price_range: '-',
    schedule: '12:30 - 21:30',
    food_type: '-',
    location: {
      id: 1249,
      latitude: '-12.124298',
      longitude: '-77.029881',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 162,
    title: 'Peluqueria Rainbow ',
    adress: ' Calle Tarata 191, LIMA 18',
    link_page: 'https://www.instagram.com/rainbowhairdesign/',
    phone: '934 990 944',
    pet_place_type_id: 1,
    location_id: 1250,
    image_card: 'pf162_rainbow1.jpeg_master',
    image_detail: 'pf162_rainbow2.jpeg',
    description:
      'Divertida Peluqueria, en la cual son recontra dog lovers, ademas de tambien hacer sesiones de fotos con perritos. Una peluqueria de artistas',
    price_range: '-',
    schedule: '11:00 - 21:00',
    food_type: '-',
    location: {
      id: 1250,
      latitude: '-12.123429',
      longitude: '-77.029501',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 163,
    title: 'Jade Tattoo',
    adress: 'Av. Alfredo Benavides 347, Miraflores 15074',
    link_page: 'https://www.instagram.com/jadeperutattoostudio/',
    phone: '959 704 892',
    pet_place_type_id: 1,
    location_id: 1252,
    image_card: 'pf163_Jade1.jpeg_master',
    image_detail: null,
    description:
      'Estudio de tatuaje muy acogedor en el cual encontraras los mejores diseños y los mejores piercings',
    price_range: '-',
    schedule: '11:00 - 20:00',
    food_type: '-',
    location: {
      id: 1252,
      latitude: '-12.124315',
      longitude: '-77.029891',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 164,
    title: 'Aeronautica',
    adress: ' Jiron Simon Salguero, 543 Santiago de Surco',
    link_page:
      'https://de-de.facebook.com/pages/category/Clothing-Store/aeronautica318/posts/',
    phone: '(01) 2716124',
    pet_place_type_id: 1,
    location_id: 1253,
    image_card: 'pf164_Aeronautica1.jpeg_master',
    image_detail: null,
    description:
      'Tienda de ropa super fresca y que va perfecto con la epoca. De exclusivo diseño',
    price_range: '-',
    schedule: '10:30 - 20:00',
    food_type: '-',
    location: {
      id: 1253,
      latitude: '-12.130131',
      longitude: '-77.008327',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Surco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 165,
    title: 'Habitat',
    adress: 'Simón Salguero 541',
    link_page: 'https://www.instagram.com/habitatclothing/',
    phone: '012711808',
    pet_place_type_id: 1,
    location_id: 1254,
    image_card: 'pf165_Habitat1.jpeg_master',
    image_detail: 'pf165_habitat2.jpeg',
    description:
      'Tienda de ropa de exclusivo diseño y muy moderna, recontra dog lovers y con la mejor atencion',
    price_range: '-',
    schedule: '10:30 - 20:00',
    food_type: '-',
    location: {
      id: 1254,
      latitude: '-12.130160',
      longitude: '-77.008300',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Surco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 166,
    title: 'Caracas Minimarket Gourmet',
    adress: 'Av. Alfredo Benavides 2428, Miraflores',
    link_page: 'https://www.instagram.com/caracasminimarket/',
    phone: '932 254 434',
    pet_place_type_id: 2,
    location_id: 1255,
    image_card: 'pf166_caracas1.jpeg_master',
    image_detail: 'pf166_caracas2.jpg',
    description:
      'Agradable Market de productos y comida venezolana, con la mejor atencion brindada. Son recontra dog lovers',
    price_range: '-',
    schedule: '07:30 - 22:00 ',
    food_type: '-',
    location: {
      id: 1255,
      latitude: '-12.128011',
      longitude: '-77.007438',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 167,
    title: 'BELLA DONNA SALON',
    adress: ' Av Mariscal Ramón Castilla 1001, Santiago de Surco',
    link_page: 'https://www.facebook.com/Bella-Donna-salon-398129027235351/',
    phone: '948 236 128',
    pet_place_type_id: 1,
    location_id: 1256,
    image_card: 'pf167_BELLA DONNA1.jpeg_master',
    image_detail: 'pf167_bella donna2.png',
    description:
      'Peluqueria muy buena con un excelente servicio, muy recomendado para cortarse el cabello o hacerse las uñas, cuenta con el mejor servicio ',
    price_range: '-',
    schedule: '09:00 - 21:00 ',
    food_type: '-',
    location: {
      id: 1256,
      latitude: '-12.135267',
      longitude: '-77.006951',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Surco',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 168,
    title: 'Blue Berry Store ',
    adress: ' Galería caracol, Av Jose Larco 101, Miraflores',
    link_page: 'https://www.instagram.com/blueberrystore_peru/',
    phone: ' 922 744 467',
    pet_place_type_id: 1,
    location_id: 1257,
    image_card: 'pf168_blue berry1.jpeg_master',
    image_detail: 'pf168_blue berry 2.png',
    description:
      'Tienda de ropa de diseñador muy buena, ubicada en larco. Son recontra dog lovers y cuentan con la mejor ropa juvenil ',
    price_range: '-',
    schedule: '10:00 - 22:00',
    food_type: '-',
    location: {
      id: 1257,
      latitude: '-12.119227',
      longitude: '-77.028533',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 169,
    title: 'InkArt Tattoo & Piercing',
    adress: ' Av. José Larco 101 - Interior 304-311 C.C. Caracol, Miraflores ',
    link_page: 'https://www.instagram.com/inkarttattooperu/',
    phone: '(01) 4440542',
    pet_place_type_id: 1,
    location_id: 1258,
    image_card: 'pf169_INKART1.jpeg_master',
    image_detail: 'pf169_INKART2.jpg',
    description:
      'Estudio de taruaje y piercing, con un concepto del arte muy bueno y genial, te atenderan muy bien. La decoracion es excelente y el trato ni que hablar.',
    price_range: '-',
    schedule: '11:00 - 21:00 ',
    food_type: '-',
    location: {
      id: 1258,
      latitude: '-12.119254',
      longitude: '-77.028519',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 170,
    title: 'Jack Vape Store',
    adress: 'AV. LARCO 101 STAND 307 CENTRO COMERCIAL, Caracol',
    link_page: 'https://www.instagram.com/jackvapestoreperu/',
    phone: '(01) 2797338',
    pet_place_type_id: 1,
    location_id: 1259,
    image_card: 'pf170_JACK1.jpeg_master',
    image_detail: 'pf170_JACK2.png',
    description:
      'tienda de vape, en la cual podras pasar un buen rato de relajo con amigos, lo mejor es que son petlovers y aceptan el ingreso con mascotas.',
    price_range: '-',
    schedule: '10:00 - 21:00',
    food_type: '-',
    location: {
      id: 1259,
      latitude: '-12.119261',
      longitude: '-77.028516',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 171,
    title: 'Jagui Store',
    adress: 'Av Jose Larco 101, Miraflores',
    link_page: 'https://www.facebook.com/Jagui.storeoficial/',
    phone: '999 858 649',
    pet_place_type_id: 1,
    location_id: 1262,
    image_card: 'pf171_Jagui Store1.jpeg_master',
    image_detail: 'pf171_Jagui2.jpg',
    description:
      'tienda de artefactos y muñecos originalmente traidos de Japon, super cool ',
    price_range: '-',
    schedule: '12:00 - 20:00',
    food_type: '-',
    location: {
      id: 1262,
      latitude: '-12.119257',
      longitude: '-77.028446',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 172,
    title: 'SimplyStore Perú',
    adress: 'Av Jose Larco 101, Miraflores',
    link_page: 'https://www.instagram.com/simplystoreperu/',
    phone: ' 962 947 579',
    pet_place_type_id: 1,
    location_id: 1263,
    image_card: 'pf172_Simply1.jpeg_master',
    image_detail: 'pf172_simply2.png',
    description:
      'tienda electronica de la mejor calidad y los mejores precios ',
    price_range: '-',
    schedule: '12:00 - 20:00',
    food_type: '-',
    location: {
      id: 1263,
      latitude: '-12.119190',
      longitude: '-77.028479',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 173,
    title: 'Ivannya barberia salon spa',
    adress: 'Av Jose Larco 321, Miraflores 15074',
    link_page: 'https://www.instagram.com/ivannyasalonspa/',
    phone: '(01) 4099062',
    pet_place_type_id: 1,
    location_id: 1264,
    image_card: 'pf173_Ivannya2.jpeg_master',
    image_detail: 'pf173_ivannya1.png',
    description:
      'Salon de belleza y barberia en el cual te podras engreir con las mejores manos y los mejores estilistas',
    price_range: '-',
    schedule: '09:00 - 20:00',
    food_type: '-',
    location: {
      id: 1264,
      latitude: '-12.119696',
      longitude: '-77.028897',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 174,
    title: 'Revival Salon ',
    adress:
      'Galeria Multicentro, interior 10, Av Jose Larco 345, Miraflores 15074',
    link_page: 'https://www.instagram.com/salonrevival/?hl=es',
    phone: ' 954 189 699',
    pet_place_type_id: 1,
    location_id: 1265,
    image_card: 'pf174_revival2.jpeg_master',
    image_detail: 'pf174_revival1.jpg',
    description:
      'Peluqueria con alta experiencia en trabajos de uñas, un trato super amable y totalmente recomendado ',
    price_range: '-',
    schedule: '10:00 - 21:00',
    food_type: '-',
    location: {
      id: 1265,
      latitude: '-12.120824',
      longitude: '-77.028865',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 175,
    title: 'Lazy It Is Discos ',
    adress: 'Galeria Multicentro Int M-5, Av Jose Larco 345, Miraflores 15074',
    link_page: 'https://www.instagram.com/lazyitisdiscos/',
    phone: '(01) 4479326',
    pet_place_type_id: 2,
    location_id: 1266,
    image_card: 'pf175_Lazyitdiscos1.jpeg_master',
    image_detail: 'pf175_Lazyitdiscos2.jpg',
    description:
      'Tienda de vinilos super cool y recontra vintage, en la cual podras encontrar de todo para todos los gustos musicales',
    price_range: '-',
    schedule: '13:00 - 20:40',
    food_type: '-',
    location: {
      id: 1266,
      latitude: '-12.120751',
      longitude: '-77.028766',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 176,
    title: 'HYHSHOP',
    adress: 'Av Jose Larco 345 Tienda M3 Galeria Multicentro Miraflores',
    link_page: 'https://www.instagram.com/hyhshop/',
    phone: '-',
    pet_place_type_id: 1,
    location_id: 1267,
    image_card: 'pf176_hyh2.jpeg_master',
    image_detail: 'pf176_hyh1.jpg',
    description:
      'tienda de accesorios, maquillaje de la mejor calidad y para todos los estilos ',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1267,
      latitude: '-12.120791',
      longitude: '-77.028807',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 177,
    title: 'Travant',
    adress: 'Calle Cantuarias 140, Miraflores 15074',
    link_page: 'https://www.instagram.com/travantstore/',
    phone: '966261243 / 992628660',
    pet_place_type_id: 1,
    location_id: 1268,
    image_card: 'pf177_travant1.jpeg_master',
    image_detail: 'pf177_travant2.jpg',
    description:
      'tienda multimarcas en la cual tambien podras encontrar accesorios para mascotas, son recontra doglovers',
    price_range: '-',
    schedule: '15:00 - 20:30',
    food_type: '-',
    location: {
      id: 1268,
      latitude: '-12.121458',
      longitude: '-77.028519',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 178,
    title: 'Pink Clue Store',
    adress: 'Calle Cantuarias 140, Miraflores 15074',
    link_page: 'https://www.instagram.com/pinkcluestore/',
    phone: '986 071 728',
    pet_place_type_id: 1,
    location_id: 1269,
    image_card: 'pf178_pink2.jpeg_master',
    image_detail: 'pf178_pink1.jpg',
    description:
      'tienda de maquillaje para los mejores estilos, su funcion es sacar la mejor version de ti ',
    price_range: '-',
    schedule: '14:30 - 20:00',
    food_type: '-',
    location: {
      id: 1269,
      latitude: '-12.121484',
      longitude: '-77.028500',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 179,
    title: 'Boutique Marialejandra',
    adress: 'Calle Cantuarias 142 Int 106, Miraflores 15074',
    link_page: 'https://www.facebook.com/alejandritaYsara/',
    phone: '995588778',
    pet_place_type_id: 1,
    location_id: 1270,
    image_card: 'pf179_marialejandra2.jpeg_master',
    image_detail: 'pf179_marialejandra1.jpg',
    description:
      ' ventas de accesorios y vestimenta, ideales para las mujeres, un concepto de la moda muy recomendado ',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1270,
      latitude: '-12.121527',
      longitude: '-77.028471',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 180,
    title: 'Valentina Joyas',
    adress:
      'Centro Comercial Cantuarias, Int. 140, Calle Cantuarias 140, Miraflores 15074',
    link_page:
      'https://es-la.facebook.com/pages/category/Interest/Valentina-Joyas-1819258618307914/',
    phone: ' 951 319 981',
    pet_place_type_id: 1,
    location_id: 1271,
    image_card: 'pf180_valentina2.jpeg_master',
    image_detail: 'pf180_valentina1.png',
    description:
      'tienda de joyeria y demas accesorios para bebes, seran parte del momento y la etapa mas linda',
    price_range: '-',
    schedule: '13:00 - 19:30',
    food_type: '-',
    location: {
      id: 1271,
      latitude: '-12.121504',
      longitude: '-77.028485',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 181,
    title: 'Hoshi Hoshi Asian Market',
    adress: 'Calle Cantuarias 140 tienda 110 (6,76 km) Case Miraflores, Peru',
    link_page: 'https://www.instagram.com/hoshihoshiasianmarket/',
    phone: '986824825',
    pet_place_type_id: 1,
    location_id: 1272,
    image_card: 'pf181_hoshi2.jpeg_master',
    image_detail: 'pf181_hoshi1.jpg',
    description:
      'El amor por toda la cultura asiática quiere llegar a tí de manera rápida y  deliciosa. Snacks, Bebidas y muchas curiosidades en Hoshi Hoshi, Asian Market. Recontra dog lovers',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1272,
      latitude: '-12.121505',
      longitude: '-77.028508',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 182,
    title: 'Lady Bug Miraflores',
    adress: ' Calle Cantuarias 140, Miraflores 15074',
    link_page: 'https://peruladybug.com/',
    phone: '991 035 059',
    pet_place_type_id: 1,
    location_id: 1273,
    image_card: 'pf182_ladybug2.jpeg_master',
    image_detail: 'pf182_ladybug1.jpg',
    description:
      'tienda de ropa con una tematica muy interesante y divertida. Quieren mucho a las mascotas',
    price_range: '-',
    schedule: '14:00 - 20:00 ',
    food_type: '-',
    location: {
      id: 1273,
      latitude: '-12.121506',
      longitude: '-77.028523',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 183,
    title: 'Galaxy Trash',
    adress:
      'Centro Comercial Cantuarias, Int 119, Calle Cantuarias 140, Miraflores 15074',
    link_page: 'https://www.instagram.com/galaxytrash/',
    phone: '-',
    pet_place_type_id: 1,
    location_id: 1274,
    image_card: 'pf183_galaxytrash1.jpeg_master',
    image_detail: 'pf183_galaxytrash2.png',
    description:
      'tienda de diseño independiente en la cual encontraras lo mas divertido y moderno, tambien podras encontrar tintes de colores muy cool ',
    price_range: '-',
    schedule: '12:00 - 8:30',
    food_type: '-',
    location: {
      id: 1274,
      latitude: '-12.121537',
      longitude: '-77.028467',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 184,
    title: 'Mystic Dragon Store',
    adress: 'Calle Cantuarias 140, Miraflores 15074',
    link_page: 'https://www.instagram.com/mysticdragon_store/',
    phone: '986 074 491',
    pet_place_type_id: 1,
    location_id: 1275,
    image_card: 'pf184_dragon1.jpeg_master',
    image_detail: 'pf184_dragon2.jpg',
    description:
      'tienda de ropa y accesorios de ambito juvenil con diseños muy divertidos y electrizantes',
    price_range: '-',
    schedule: '09:00 - 21:00 t',
    food_type: '-',
    location: {
      id: 1275,
      latitude: '-12.121471',
      longitude: '-77.028470',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 185,
    title: 'La Maleta Secreta Store',
    adress:
      'Centro Comercial Cantuarias, Int 134, Calle Cantuarias 140, Miraflores 15074',
    link_page: 'https://es-la.facebook.com/lamaletasecretastore/',
    phone: '983 707 173',
    pet_place_type_id: 1,
    location_id: 1276,
    image_card: 'pf185_maleta2.jpeg_master',
    image_detail: 'pf185_maleta1.png',
    description:
      'tienda de ropa, con diseños de dibujos animados muy cool, ademas tambien venden accesorios muy buenos',
    price_range: '-',
    schedule: '11:30 - 20:30 ',
    food_type: '-',
    location: {
      id: 1276,
      latitude: '-12.121491',
      longitude: '-77.028523',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 186,
    title: 'Ohana Store',
    adress: 'Calle Cantuarias 140 ',
    link_page: 'https://www.instagram.com/ohanastorepe/',
    phone: '947198852',
    pet_place_type_id: 1,
    location_id: 1277,
    image_card: 'pf186_ohana2.jpeg_master',
    image_detail: 'pf186_ohana1.jpg',
    description:
      'tienda de las mejores zapatillas de la mejor calidad y mejores diseños ',
    price_range: '-',
    schedule: '14:30 - 20:00 ',
    food_type: '-',
    location: {
      id: 1277,
      latitude: '-12.121449',
      longitude: '-77.028511',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 187,
    title: 'Impo XP',
    adress: 'Calle Cantuarias 140, Miraflores 15074',
    link_page: 'https://www.facebook.com/pg/impoxp/posts/',
    phone: ' 917 849 536',
    pet_place_type_id: 1,
    location_id: 1278,
    image_card: 'pf187_impoxp1.png_master',
    image_detail: null,
    description:
      'servicio de importacion muy bueno, confiable y super recomendado ',
    price_range: '-',
    schedule: '14:00 - 20:00',
    food_type: '-',
    location: {
      id: 1278,
      latitude: '-12.121479',
      longitude: '-77.028490',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 188,
    title: "L'art Perú",
    adress:
      'Centro Comercial Cantuarias, Calle Cantuarias 140, Miraflores 15074',
    link_page: 'https://es-la.facebook.com/Lartperu',
    phone: '(01) 2410814',
    pet_place_type_id: 1,
    location_id: 1279,
    image_card: 'pf188_lart2.jpeg_master',
    image_detail: 'pf188_lart1.jpg',
    description:
      'tienda de instrumentos musicales y escuela de musica en la cual aprenderas de la mejor manera y haras muchos amigos ',
    price_range: '-',
    schedule: '09:00 - 21:00',
    food_type: '-',
    location: {
      id: 1279,
      latitude: '-12.121491',
      longitude: '-77.028535',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 189,
    title: 'Butterfly Closet by Antonio Tafur ',
    adress: 'Calle Cantuarias 140, Miraflores 15074',
    link_page: 'https://www.instagram.com/bcloset.pe/',
    phone: '936363610',
    pet_place_type_id: 1,
    location_id: 1280,
    image_card: 'pf189_butterfly1.jpeg_master',
    image_detail: null,
    description:
      'tienda de ropa del mejor diseño y del mejor diseñador, Antonio Tafur, reconocido personaje de la farandula y recontra dog lover ',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1280,
      latitude: '-12.121533',
      longitude: '-77.028506',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'Miraflores',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 190,
    title: 'Quokka Coffee Shop',
    adress: 'Calle Las Palmeras 443, San Isidro 15073',
    link_page: 'https://www.instagram.com/quokkacoffeeshop/?hl=es-la',
    phone: '(01) 4836392',
    pet_place_type_id: 2,
    location_id: 1281,
    image_card: 'pf190_quokka2.jpeg_master',
    image_detail: 'pf190_quokka1.jpg',
    description:
      'Cafeteria con una ambientacion muy relajante y asombrosa, los mejores productos y el cafe mas rico los encuentras aqui, ademas son recontra dog lovers y ecologicos. ',
    price_range: '-',
    schedule: '07:30 - 21:00 ',
    food_type: '-',
    location: {
      id: 1281,
      latitude: '-12.095290',
      longitude: '-77.038354',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'San Isidro',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 191,
    title: 'SETTIMANA',
    adress: 'Av Camino Real ',
    link_page: 'https://www.facebook.com/www.settimana.com.pe',
    phone: '-',
    pet_place_type_id: 1,
    location_id: 1282,
    image_card: 'pf191_settimana2.jpeg_master',
    image_detail: 'pf191_settimana1.jpg',
    description:
      'tienda de ropa de mujer de muy buena calidad y muy buen diseño, podras encontrar para todos los gustos ',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1282,
      latitude: '-12.097653',
      longitude: '-77.036395',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'San Isidro',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 192,
    title: 'Fly and Fun Globos de Helio ',
    adress: ' Av. Camino Real #497 Tda 116 San Isidro - Lima Perú',
    link_page: 'http://www.fly-funglobosdehelio.com/',
    phone: '947-746-016',
    pet_place_type_id: 1,
    location_id: 1283,
    image_card: 'pf192_globos1.jpeg_master',
    image_detail: 'pf192_globos2.jpg',
    description:
      'tienda de globos de helio, para todo tipo de fiestas, tendras el mejor asesoramiento posible, para lograr divertirte a full',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1283,
      latitude: '-12.098853',
      longitude: '-77.036863',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'San Isidro',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 193,
    title: 'Sami Lovers',
    adress: 'Avenida Camino Real 497',
    link_page: 'https://www.facebook.com/SAMIBYLOVERS/',
    phone: ' 977924321',
    pet_place_type_id: 1,
    location_id: 1284,
    image_card: 'pf193_sami2.jpeg_master',
    image_detail: 'pf193_sami1.jpg',
    description:
      'joyas americanas exclusivas con diseño personalizado, super recomendado\n',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1284,
      latitude: '-12.091824',
      longitude: '-77.030004',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'San Isidro',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 194,
    title: 'Bobble Store',
    adress: 'Av Camino Real 347',
    link_page:
      'https://www.google.com.pe/search?sxsrf=ALeKk01Lz3N6oCED2KtdcGUFDWfKnJNOmw%3A1583128067638&source=hp&ei=A55cXsGbJdbE5OUPsKCj4AQ&q=bobble+tienda&oq=bobble+tienda&gs_l=psy-ab.3..0i13l3j0i13i30l2j0i13i5i30l2j0i8i13i30l3.12715.22789..23715...1.0..0.895.4141.6j1j0j2j1j1j2......0....1..gws-wiz.......35i39j0i131j0j0i67j0i10j0i203j0i22i10i30j0i22i30j33i160..23%3A0g922g847g167g105g105g101g101g107g105g435j24%3A0g1g1g1g1g1g1g1g1g1g4.guvVXlpvEuI&ved=0ahUKEwiBqerQi_vnAhVWIrkGHTDQCEwQ4dUDCAc&uact=5',
    phone: '-',
    pet_place_type_id: 2,
    location_id: 1285,
    image_card: 'pf194_bobble1.jpeg_master',
    image_detail: null,
    description:
      'tienda de zapatos de muy buen diseño, para todos los gustos y modas ',
    price_range: '-',
    schedule: '-',
    food_type: '-',
    location: {
      id: 1285,
      latitude: '-12.098850',
      longitude: '-77.036863',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'San Isidro',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 195,
    title: 'Estrella Untiveros Shoes',
    adress: 'Av. Camino Real 497, San Isidro 15073',
    link_page: 'http://www.estrellauntiverosshoes.com/',
    phone: ' 987 849 443',
    pet_place_type_id: 1,
    location_id: 1286,
    image_card: 'pf195_untiveros2.jpeg_master',
    image_detail: 'pf195_untiveros1.jpg',
    description:
      'Tienda de zapatos que busca dedicar su arte y tecnología en la creación de nuevos diseños, en colaboración de un grupo humano que busca la excelencia y cumpliendo con la plena satisfacción del cliente.',
    price_range: '-',
    schedule: '11:00 - 20:00 ',
    food_type: '-',
    location: {
      id: 1286,
      latitude: '-12.098851',
      longitude: '-77.036900',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'San Isidro',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 196,
    title: 'The Poppy Shop',
    adress: 'Av. Camino Real 497, San Isidro 15073',
    link_page: 'https://www.instagram.com/holapoppyshop/?hl=es-la',
    phone: '930 137 693',
    pet_place_type_id: 1,
    location_id: 1287,
    image_card: 'pf196_poppy1.jpeg_master',
    image_detail: 'pf196_poppy2.jpeg',
    description:
      'Tienda de multibrand de emprendedoras, que cuentan con la mejor ropa y los mejores accesorios',
    price_range: '-',
    schedule: '11:00 - 20:00',
    food_type: '-',
    location: {
      id: 1287,
      latitude: '-12.098867',
      longitude: '-77.036922',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'San Isidro',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 197,
    title: 'Cremeria Toscana Perú',
    adress:
      'Avenida Conquistadores 325 San Isidro Municipalidad Metropolitana de Lima',
    link_page: 'https://www.facebook.com/cremeriatoscanaperu/',
    phone: '(01) 7634479',
    pet_place_type_id: 2,
    location_id: 1288,
    image_card: 'pf197_toscana1.jpeg_master',
    image_detail: 'pf197_toscana2.png',
    description:
      'Heladeria artesanal con los mejores sabores de helado, cuenta con un ambiente muy bonito y agradable para compartir en familia y junto a la compañia de tu mascota.',
    price_range: '-',
    schedule: '11:00 - 21:00 ',
    food_type: '-',
    location: {
      id: 1288,
      latitude: '-12.099314',
      longitude: '-77.036260',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'San Isidro',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 198,
    title: 'DAFIN AND DESIGN JOYAS',
    adress: 'Av. Los Conquistadores 325, San Isidro 15073',
    link_page:
      'https://www.facebook.com/pages/Dafin-and-Design/133421000430787?hc_ref=ARTMZDhf_Kx8XgWHaVlYx-xoAEQgNNz2yABzxul4KQgr2h6tPFZ-vN3oUunjYwSaPKs',
    phone: '-',
    pet_place_type_id: 1,
    location_id: 1289,
    image_card: 'pf198_dafin1.jpeg_master',
    image_detail: null,
    description:
      'lugar de exclusivo diseño de joyas, con las formas mas creativas e innovadoras',
    price_range: '-',
    schedule: '10:00 - 19:00',
    food_type: '-',
    location: {
      id: 1289,
      latitude: '-12.099383',
      longitude: '-77.036334',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'San Isidro',
      abreviated: null,
      user_id: null,
    },
  },
  {
    id: 199,
    title: 'Fasce',
    adress: 'Av. Conquistadores 325, San Isidro',
    link_page: 'https://fasceclothing.com/',
    phone: '947799125',
    pet_place_type_id: 1,
    location_id: 1290,
    image_card: 'pf199_fasce2.jpeg_master',
    image_detail: 'pf199_fasce1.png',
    description:
      'marca con diseños frescos y diferentes dirigido a mujeres que aman con pasión la vida y que se aman por sobre todas las cosas a sí mismas.',
    price_range: '-',
    schedule: '11 am a 8 pm',
    food_type: '-',
    location: {
      id: 1290,
      latitude: '-12.098352',
      longitude: '-77.036214',
      country: 'Perú',
      city: 'Lima',
      department: '',
      zipcode: '',
      province: '',
      district: 'San Isidro',
      abreviated: null,
      user_id: null,
    },
  },
];
